keys:
  - &users:
    - &quantinium age1mnzjr0hwqdq7wt3zs65q63kyt7lqctswwk7v8xrar5rfjmd0feyqg4zdqm
  - &hosts:
    - &nixie age1dhzfeg90czpc2crq6q7gxv722uq2c2pza48knt7jek943a6vwg8szs7x95
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *quantinium
      - *nixie

