keys:
  - &quantinium age1s4a2pre0gvt7p5f53mhnvy8zn673sd7lhyjy4z9w2g95cnm39qhs0w0a98
  - &nixie age1dhzfeg90czpc2crq6q7gxv722uq2c2pza48knt7jek943a6vwg8szs7x95
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *quantinium
      - *nixie

