# Auto-generated by compose2nix.
{ pkgs, lib, config, ... }:

{
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  virtualisation.oci-containers.containers."eris-app" = {
    image = "ghcr.io/quantinium3/eris:v-0.1.0";
    environment = {
      "DATABASE_URL" = "";
      "LASTFM_APIKEY" = "";
      "LASTFM_URI" = "";
      "LASTFM_USERNAME" = "";
    };
    ports = [
      "3000:3000/tcp"
    ];
    dependsOn = [
      "eris-db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=app"
      "--network=eris_default"
    ];
  };
  systemd.services."podman-eris-app" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-eris_default.service"
    ];
    requires = [
      "podman-network-eris_default.service"
    ];
    partOf = [
      "podman-compose-eris-root.target"
    ];
    wantedBy = [
      "podman-compose-eris-root.target"
    ];
  };
  virtualisation.oci-containers.containers."eris-db" = {
    image = "postgres";
    environment = {
      "POSTGRES_DB" = "";
      "POSTGRES_PASSWORD" = "";
      "POSTGRES_USER" = "";
    };
    volumes = [
      "eris_postgres_data:/var/lib/postgresql/data:rw"
    ];
    ports = [
      "5432:5432/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=pg_isready -U eris_user -d eris_db"
      "--health-interval=10s"
      "--health-retries=5"
      "--health-timeout=5s"
      "--network-alias=db"
      "--network=eris_default"
    ];
  };
  systemd.services."podman-eris-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-eris_default.service"
      "podman-volume-eris_postgres_data.service"
    ];
    requires = [
      "podman-network-eris_default.service"
      "podman-volume-eris_postgres_data.service"
    ];
    partOf = [
      "podman-compose-eris-root.target"
    ];
    wantedBy = [
      "podman-compose-eris-root.target"
    ];
  };

  systemd.services."podman-network-eris_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f eris_default";
    };
    script = ''
      podman network inspect eris_default || podman network create eris_default
    '';
    partOf = [ "podman-compose-eris-root.target" ];
    wantedBy = [ "podman-compose-eris-root.target" ];
  };

  systemd.services."podman-volume-eris_postgres_data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect eris_postgres_data || podman volume create eris_postgres_data
    '';
    partOf = [ "podman-compose-eris-root.target" ];
    wantedBy = [ "podman-compose-eris-root.target" ];
  };

  systemd.targets."podman-compose-eris-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}

