{ pkgs, lib, config, ... }:

{
	sops.secrets = {
		"services/xunback/env" = { };
		"services/xunback-db/env" = { };
	};

  virtualisation.oci-containers.containers."xunback-app" = {
    image = "ghcr.io/xunback:v-0.1.0";
		environmentFiles = [
			config.sops.secrets."services/xunback/env".path
		];
    ports = [
      "3001:3000/tcp"
    ];
    dependsOn = [
      "xunback-db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=app"
      "--network=xunback_default"
    ];
  };
  systemd.services."podman-xunback-app" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-xunback_default.service"
    ];
    requires = [
      "podman-network-xunback_default.service"
    ];
    partOf = [
      "podman-compose-xunback-root.target"
    ];
    wantedBy = [
      "podman-compose-xunback-root.target"
    ];
  };
  virtualisation.oci-containers.containers."xunback-db" = {
    image = "postgres:16-alpine";
		environmentFiles = [
			config.sops.secrets."services/xunback-db/env".path
		];
    volumes = [
      "xunback_postgres_data:/var/lib/postgresql/data:rw"
    ];
    ports = [
      "5432:5432/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=pg_isready -U xunbao_user -d xunbao_db"
      "--health-interval=10s"
      "--health-retries=5"
      "--health-timeout=5s"
      "--network-alias=db"
      "--network=xunback_default"
    ];
  };
  systemd.services."podman-xunback-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-xunback_default.service"
      "podman-volume-xunback_postgres_data.service"
    ];
    requires = [
      "podman-network-xunback_default.service"
      "podman-volume-xunback_postgres_data.service"
    ];
    partOf = [
      "podman-compose-xunback-root.target"
    ];
    wantedBy = [
      "podman-compose-xunback-root.target"
    ];
  };

  systemd.services."podman-network-xunback_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f xunback_default";
    };
    script = ''
      podman network inspect xunback_default || podman network create xunback_default
    '';
    partOf = [ "podman-compose-xunback-root.target" ];
    wantedBy = [ "podman-compose-xunback-root.target" ];
  };

  systemd.services."podman-volume-xunback_postgres_data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect xunback_postgres_data || podman volume create xunback_postgres_data
    '';
    partOf = [ "podman-compose-xunback-root.target" ];
    wantedBy = [ "podman-compose-xunback-root.target" ];
  };

  systemd.targets."podman-compose-xunback-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
