{ pkgs, lib, config, ... }:

{
	sops.secrets = {
		"services/xunback/env" = { };
	};
	/*
		1. Create the user and database manually:
		sudo podman exec -it eris-db psql -U eris_user -d eris_db

		CREATE USER xunback_user WITH PASSWORD 'xunback_password';
		CREATE DATABASE xunback_db OWNER xunback_user;
		GRANT ALL PRIVILEGES ON DATABASE xunback_db TO xunback_user;
		\q
	*/

  virtualisation.oci-containers.containers."xunback-app" = {
    image = "ghcr.io/quantinium3/xunback:v-0.1.0";
		environmentFiles = [
			config.sops.secrets."services/xunback/env".path
		];
    ports = [
      "3001:3000/tcp"
    ];
    dependsOn = [
      "eris-db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=xunback-app"
      "--network=nixie"
    ];
  };
  systemd.services."podman-xunback-app" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-nixie.service"
      "podman-eris-db.service"
    ];
    requires = [
      "podman-network-nixie.service"
      "podman-eris-db.service"
    ];
    partOf = [
      "podman-compose-xunback-root.target"
    ];
    wantedBy = [
      "podman-compose-xunback-root.target"
    ];
  };

  systemd.targets."podman-compose-xunback-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
